/**
 * Exporter: DesignTokens → globals.css (CSS custom properties).
 *
 * Generates a `:root` block and a `.dark` override when mode is "both".
 * For Tailwind v4 projects, the @theme block is appended via tailwind.ts.
 */
import type { DesignTokens } from "@design-md/schema";

import { TW_COLORS } from "./tw-colors.js";

function tokenToVar(token: string | undefined): string {
  if (!token) return "unset";
  if (token.startsWith("tw:")) {
    const tw = token.slice(3);
    return TW_COLORS[tw] ?? `/* ${tw} */`;
  }
  return token;
}

export function toCssVars(tokens: DesignTokens, tailwindVersion: 2 | 3 | 4 = 3): string {
  const lines: string[] = [
    `/* Generated by design-md-kit — brand: ${tokens.meta.name} */`,
    `/* Source: ${tokens.meta.source ?? "local"} */`,
    "",
    '@import url("https://fonts.googleapis.com/css2?family=' +
      [
        tokens.typography.fontFamilies?.display,
        tokens.typography.fontFamilies?.body,
        tokens.typography.fontFamilies?.mono,
      ]
        .filter(Boolean)
        .map((f) => `${f!.replace(/ /g, "+")}:wght@300;400;500;600;700`)
        .join("&family=") +
      '&display=swap");',
    "",
    ":root {",
    `  /* Brand: ${tokens.meta.name} — ${tokens.theme.aesthetic ?? tokens.theme.mode} */`,
  ];

  // Palette
  const roles = ["background", "foreground", "surface", "border", "accent", "muted"] as const;
  for (const role of roles) {
    const val = tokens.palette[role];
    if (typeof val === "string") {
      lines.push(`  --color-${role}: ${tokenToVar(val)};`);
    }
  }

  // Typography
  const ff = tokens.typography.fontFamilies;
  if (ff?.display) lines.push(`  --font-display: "${ff.display}", sans-serif;`);
  if (ff?.body) lines.push(`  --font-body: "${ff.body}", sans-serif;`);
  if (ff?.mono) lines.push(`  --font-mono: "${ff.mono}", monospace;`);

  // Motion
  if (tokens.motion.durations) {
    const d = tokens.motion.durations;
    if (d.fast) lines.push(`  --duration-fast: ${d.fast};`);
    if (d.normal) lines.push(`  --duration-normal: ${d.normal};`);
    if (d.slow) lines.push(`  --duration-slow: ${d.slow};`);
  }

  // Dials as CSS vars — useful for JS-driven style overrides.
  lines.push(`  --design-variance: ${tokens.dials.design_variance};`);
  lines.push(`  --motion-intensity: ${tokens.dials.motion_intensity};`);
  lines.push(`  --visual-density: ${tokens.dials.visual_density};`);

  lines.push("}");

  // Tailwind v4 @theme block appended for reference.
  if (tailwindVersion === 4) {
    lines.push("");
    lines.push("/* Tailwind v4 — @theme overrides */");
    lines.push("/* Paste the block from tailwind.css if needed */");
  }

  return lines.join("\n") + "\n";
}
