/**
 * Exporter: DesignTokens → tailwind.config.js (v3) or tailwind.config.ts (v4 CSS-vars mode).
 *
 * We don't write a full theme override — we merge into the `extend` block so the
 * project's existing Tailwind config stays intact. The consumer can always promote
 * tokens to the top-level `theme` if they want to override Tailwind defaults.
 */
import type { DesignTokens } from "@design-md/schema";
import { TW_COLORS } from "./tw-colors.js";

export type TailwindVersion = 3 | 4;

/** Resolve a `tw:` prefixed token to a hex/rgba value or CSS comment fallback. */
function resolveToken(token: string | undefined): string | undefined {
  if (!token) return undefined;
  if (token.startsWith("tw:")) {
    const tw = token.slice(3);
    return TW_COLORS[tw] ?? `/* ${tw} */`;
  }
  return token;
}

/** Build the `colors` extension object from the palette. */
function buildColors(palette: DesignTokens["palette"]): Record<string, unknown> {
  const colors: Record<string, unknown> = {};
  const roles = [
    "background",
    "foreground",
    "surface",
    "border",
    "accent",
    "muted",
  ] as const;

  for (const role of roles) {
    const val = palette[role];
    if (!val) continue;
    if (typeof val === "string") {
      colors[role] = resolveToken(val) ?? val;
    } else {
      const scale: Record<string, string> = {};
      for (const [k, v] of Object.entries(val)) {
        if (typeof v === "string") scale[k] = resolveToken(v) ?? v;
      }
      colors[role] = scale;
    }
  }

  if (palette.custom) {
    for (const [k, v] of Object.entries(palette.custom)) {
      if (typeof v === "string") colors[k] = resolveToken(v) ?? v;
    }
  }

  return colors;
}

/** Build the `fontFamily` extension object from typography. */
function buildFontFamilies(
  typo: DesignTokens["typography"],
): Record<string, string[]> {
  const fonts: Record<string, string[]> = {};
  const ff = typo.fontFamilies;
  if (!ff) return fonts;
  if (ff.display) fonts["display"] = [ff.display, "sans-serif"];
  if (ff.body) fonts["sans"] = [ff.body, "sans-serif"];
  if (ff.mono) fonts["mono"] = [ff.mono, "monospace"];
  return fonts;
}

/** Generate a tailwind.config.js (v3) string for the given tokens. */
export function toTailwindV3(tokens: DesignTokens): string {
  const colors = buildColors(tokens.palette);
  const fontFamily = buildFontFamilies(tokens.typography);
  const hasColors = Object.keys(colors).length > 0;
  const hasFonts = Object.keys(fontFamily).length > 0;

  const extendBlock = [
    hasColors ? `      colors: ${JSON.stringify(colors, null, 8).replace(/\n/g, "\n      ")},` : "",
    hasFonts ? `      fontFamily: ${JSON.stringify(fontFamily, null, 8).replace(/\n/g, "\n      ")},` : "",
  ]
    .filter(Boolean)
    .join("\n");

  return `/** @type {import('tailwindcss').Config} */
// Generated by design-md-kit — brand: ${tokens.meta.name}
// Edit tokens in ./design/${tokens.meta.slug}/DESIGN.md, then re-run: npx design-md add ${tokens.meta.slug}
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: ${tokens.theme.mode === "both" ? '"class"' : '"media"'},
  theme: {
    extend: {
${extendBlock}
    },
  },
  plugins: [],
};
`;
}

/**
 * Generate a @theme block for Tailwind v4 (CSS-first config).
 * In v4 there is no tailwind.config.js — tokens live in globals.css under @theme.
 */
export function toTailwindV4ThemeBlock(tokens: DesignTokens): string {
  const lines: string[] = ["@theme {", `  /* Brand: ${tokens.meta.name} */`];

  const paletteRoles = ["background", "foreground", "surface", "border", "accent", "muted"] as const;
  for (const role of paletteRoles) {
    const val = tokens.palette[role];
    if (typeof val === "string") {
      const resolved = val.startsWith("tw:") ? `/* ${val.slice(3)} */` : val;
      lines.push(`  --color-${role}: ${resolved};`);
    }
  }

  const ff = tokens.typography.fontFamilies;
  if (ff?.display) lines.push(`  --font-display: "${ff.display}", sans-serif;`);
  if (ff?.body) lines.push(`  --font-sans: "${ff.body}", sans-serif;`);
  if (ff?.mono) lines.push(`  --font-mono: "${ff.mono}", monospace;`);

  lines.push("}");
  return lines.join("\n");
}
